name: CI Pipeline

on:
  push:
    branches: [ main ]
 
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t '${{secrets.DOCKER_USERNAME}}'/cluster-dashboard:'${{github.sha}}' .
    
    - name: Log in to Docker Hub
      run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

    - name: Push Docker Image
      run: docker push '${{secrets.DOCKER_USERNAME}}'/cluster-dashboard:'${{github.sha}}'

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull '${{secrets.DOCKER_USERNAME}}'/cluster-dashboard:'${{github.sha}}'
    
    - name: Run Test
      run: docker run -d --name cluster-dashboard -p 9000:9000 '${{secrets.DOCKER_USERNAME}}'/cluster-dashboard:'${{github.sha}}'
   
    - name: Test container
      run: |
        sleep 20
        curl -f http://localhost:9000/ || (docker logs cluster-dashboard && exit 1)

    - name : Stop Container
      run: |
        docker stop cluster-dashboard
        docker rm cluster-dashboard